### ISSUE TITLE
Add font selection

### ISSUE THREAD

**Issue by ulrmdhn** [sirilius/watermarkktp#1]
Can we add font selection for the watermark?

**Comment by sirilius** [comment]
Of course it can. In the next update I will add a choice of font size, font family, and font transparancy.

**Comment by ulrmdhn** [comment]
I already made the font selection, can I PR that so you can check my code?

**Comment by ulrmdhn** [comment]
https://github.com/sirilius/watermarkktp/pull/2 done.
