### ISSUE TITLE
refactor: Migrate to dynamic templating

### ISSUE THREAD

**Issue by codenoid** [sirilius/watermarkktp#34]
Backend & Technology monggo creator yang menentukan

**Comment by sirilius** [comment]
Aku kurang paham dengan dynamic templating nih kak, mungkin bisa dijelaskan artinya?

**Comment by codenoid** [comment]
jadi kan gini mas, aku tadi nambah fitur share button, eh aku baru sadar, kok muncul nya di halaman index doang?, oh iya ternyata masih static html, dan perlu nambah di file-file lain juga

nah fungsi dynamic templating disini supaya mengurangi tingkat repetitive kita (sebagai developer) mas

**Comment by sirilius** [comment]
Mungkin ini akan aku terapin kak, tapi aku masih butuh waktu untuk memikirkannya.

**Comment by diosamuel** [comment]
> Mungkin ini akan aku terapin kak, tapi aku masih butuh waktu untuk memikirkannya.

bagaimana yang simpel seperti webcomponent ? sepertinya bagus

**Comment by diosamuel** [comment]
> > Mungkin ini akan aku terapin kak, tapi aku masih butuh waktu untuk memikirkannya.
> 
> bagaimana yang simpel seperti webcomponent ? sepertinya bagus, mengurangi pengulangan elemen html

**Comment by sirilius** [comment]
Halo @codenoid!

Setelah kita migrate ke Eleventy, dynamic templating udah bisa kita pakai untuk memudahkan proses development. Thank you udah open issue ini, aku tutup sekarang :+1:
