### ISSUE TITLE
feat: Add (website) to home screen

### ISSUE THREAD

**Issue by codenoid** [sirilius/watermarkktp#35]
- [https://stackoverflow.com/questions/38826397/add-to-home-screen-functionality-using-javascript](https://stackoverflow.com/questions/38826397/add-to-home-screen-functionality-using-javascript)

**Comment by sirilius** [comment]
Terima kasih sarannya kak. Untuk menghindari kepenuhan tombol, fitur ini tidak aku tambahkan dulu kak :pray:

**Comment by codenoid** [comment]
kok langsung di close terus ka :disappointed: , kita diskusi dulu boleh?

**Comment by codenoid** [comment]
Jadi "Add to home screen" yang ini sama sekali ngga nambah element untuk button mas, alias browser sendiri yang akan invoke ke user
