### ISSUE TITLE
output canvas blank in mobile view

### ISSUE THREAD

**Issue by fngadiyo** [sirilius/watermarkktp#39]
![IMG_20211110_173547](https://user-images.githubusercontent.com/73419981/141098001-ac38434f-234f-4816-b01d-669ddb5b83c8.jpg)

**Comment by sirilius** [comment]
Halo kak, terima kasih sudah membuka issue ini.

Untuk tampilan mobile memang aku buat blank, karena pengguna mobile tidak bisa drag file.

Mungkin, nantinya aku akan menambahkan placeholder seperti di tampilan dekstop. Tapi dengan bentuk yang berbeda.
