### ISSUE TITLE
[Feature Request] Multilanguage Support

### ISSUE THREAD

**Issue by forbiddenmanu** [sirilius/watermarkktp#41]
It would be a nice idea to have multilanguage support for this site. So non-Indonesian citizens can also enjoy this service!
I'm adding English-ltranslated README to [my own fork](https://github.com/forbiddenmanu/watermarkktp). And if you agree, I will make a PR for it.

Anyways, hello! I'm Hendra Manudinata, a 14 y.o teenager, just like you! Nice to meet you, indirectly.

---

Akan menjadi ide bagus jika ditambahkan untuk situs ini. Jadinya, warga non-Indonesia juga dapat menikmati layanan ini.
Saya lagi menambah terjemahan Inggris untuk README ke [fork personal](https://github.com/forbiddenmanu/watermarkktp). Dan jika Kakak setuju, saya akan buat PR untuk itu.

Oh iya, halo, Kak! Saya Hendra Manudinata, remaja 14 tahun, sama seperti Kakak. Senang dapat bertemu Kakak, secara tidak langsung.

**Comment by forbiddenmanu** [comment]
Done. Now I'm working on whole site translation. Still, _under your command, Sir!_.

---

Sip, kelar. Sekarang saya sedang menerjemahkan seluruh situs. Tapi, tetap saja, _Dibawah komando Anda, Pak!_.

**Comment by sirilius** [comment]
Hello Hendra, nice to meet you too 👋

Thanks for your suggestion. Jujur aja aku masih ragu untuk menambahkan dukungan multilanguage untuk Watermark KTP melihat fokus alat ini ditujukan untuk teman-teman yang berbahasa Indonesia saja.

Karena aku ingin membuatnya sesederhana mungkin, jadi penambahan ini mungkin belum menjadi prioritas sekarang. Aku akan melihatnya lagi di depan, apakah kita memang membutuhkannya atau tidak.

Terima kasih sekali lagi :)

**Comment by forbiddenmanu** [comment]
Thank you very much for the reply.

Siap, Kak. Memang, mayoritas pengguna situs ini adalah warga Indonesia.

Kalau begitu, saya akan sambil menambah beberapa peningkatan, termasuk dynamic templating (#34). Perubahan akan tersedia di [fork saya](https://github.com/forbiddenmanu/watermarkktp).

Makasih, Kak!

**Comment by sirilius** [comment]
Terima kasih kembali 😊
