### ISSUE TITLE
Menggunakan bundler untuk kemudahan development

### ISSUE THREAD

**Issue by reacto11mecha** [sirilius/watermarkktp#53]
Pada saat development ketika sedang mengubah js agak merasa kesulitan, dimana mesti jalanin `npm run min` setiap kali punya perubahan di js atau di css. Cara lain mengubah path js/css nya di htmlnya ke versi yang belum di minified, tapi akan jadi masalah ketika htmlnya ikutan kena commit. Saran pake bundler atau frontend tooling kayak [vite](https://vitejs.dev/) biar lebih gampang develop web ini. Vite ini nantinya bakalan minified nggak js doang, html sama css udah otomatis di minfied ukurannya pada saat mode production, support juga di deploy ke [netlify](https://vitejs.dev/guide/static-deploy.html#netlify). Pada saat ada perubahan di mode dev, dia otomatis refresh halaman, nggak perlu capek-capek lagi refresh manual

**Comment by sirilius** [comment]
Thank you atas sarannya. Akan aku pikirkan ya.

**Comment by sirilius** [comment]
Halo @reacto11mecha! Karena kita udah migrate ke Eleventy yang bisa minified JS, HTML, dan CSS secara otomatis, aku close issue ini yaa. Terima kasih.

**Comment by reacto11mecha** [comment]
Siap, sama sama
