### ISSUE TITLE
Confusing behavior on auto-watermarking

### ISSUE THREAD

**Issue by codenoid** [sirilius/watermarkktp#64]
## Issue 

Setelah update terbaru, saya melihat ada fitur baru yang otomatis menambahkan text __Verifikasi, 26-7-2022__ secara dinamis ke caption watermark, ini bagus, tapi pengaplikasiannya mungkin masih kurang tepat:

beberapa bug(?) yang ditemukan:

```
1. CTRL+R
    -> tulis caption watermark
    -> tambah gambar 
    -> watermark yang sudah ditulis otomatis terganti menjadi *Verifikasi, 26-7-2022*

2. CTRL+R
    -> klik "reset"
    -> caption watermark otomatis terganti menjadi *Verifikasi, 26-7-2022*, padahal awalnya kosong
```

Related code:

https://github.com/sirilius/watermarkktp/blob/2eaa0de5b3a1679ceac596319a947ad23a413591/src/_includes/js/watermark.js#L215-L236

## Suggestion

Yang pertama, bagaimana kalau kita menambahkan field baru diatas field **Font**, nama field nya **Template Watermark**, contoh sebagai berikut ini:

![image](https://user-images.githubusercontent.com/14269809/180848257-1493aee5-8ab7-423c-aca5-1c12a2e862b0.png)

Kedua, by default, biarkan caption watermark kosong, supaya pengguna2 yang sebelumnya tidak bingung dengan perubahan terbaru ini, apalagi pengguna2 tua seperti saya yang kadang masih minta tolong orang untuk mempelajari aplikasi

jadi semisal ada perubahan value tetap atas dasar consent pengguna

**Comment by sirilius** [comment]
Hallo @codenoid , Thank you sudah membuka issue ini.

Sepertinya ini akan bagus untuk diaplikasikan pada Watermark KTP.  Akan aku coba untuk mengeksperimenkannya.

**Comment by sirilius** [comment]
Done!
